FROM mcr.microsoft.com/dotnet/sdk:8.0
WORKDIR /app

COPY . .
WORKDIR /app/src/OpenDirectoryDownloader
RUN dotnet publish -c Release -o out

RUN apt-get update && apt-get install -y python3 python3-pip python3-flask gunicorn

RUN chmod +x build.sh
RUN ./build.sh

ENTRYPOINT ["gunicorn", "-w", "8", "-b", "0.0.0.0:5000", "--timeout", "600", "api_wrapper:app"]
# CMD ["tail", "-f", "/dev/null"]
